services:
  postgres:
    image: postgres:15
    container_name: openhands-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.31-nikolaik}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of openhands-state for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database_net

  pgbouncer:
    image: edoburu/pgbouncer

    environment:
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=postgres
      - DB_NAME=$POSTGRES_DB
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres,$POSTGRES_USER
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
      - MIN_POOL_SIZE=0
      - AUTH_TYPE=scram-sha-256
    ports:
      - "6432:5432"

    restart: on-failure

    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-h",
          "postgres",
          "-p",
          "5432",
        ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - database_net
    depends_on:
      - postgres

volumes:
  postgres_data:
networks:
  database_net:
